import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/providers/query.provider";
import AuthProvider from "@/providers/auth.provider";
import CssBaseline from "@mui/material/CssBaseline";
import { MaterialUIControllerProvider } from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/assets/theme";
import LayoutProvider from "@/providers/layout.provider";
import "material-icons/iconfont/material-icons.css";
import Snackbar from "@/components/Snackbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MaterialUIControllerProvider>
            <LayoutProvider>
              <QueryProvider>{children}</QueryProvider>
            </LayoutProvider>
          </MaterialUIControllerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
