name: PROD DEPLOY

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=$GITHUB_REF" >> $GITHUB_ENV

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: prod-backstage-app
          dontuseforce: false
